### ISSUE TITLE
1px overflow on TD of full width image

### ISSUE THREAD

**Issue by vz01d** [emailmonday/Cerberus#247] opened 2020-06-26 18:13 UTC
**Describe the bug**
I can see an 1px overflow to the right of the full width image in all 3 templates (responsive, hybrid, fluid) which hurts layout a bit.

**To Reproduce**
1. Which template? (there are three) -> all of them
2. Which email clients and/or devices are affected? -> win10 (outlook) mail-app (desktop) it's that default email client shipped with win10

**Screenshots**
![grafik](https://user-images.githubusercontent.com/52013886/85888126-44ef0700-b7e9-11ea-921b-ba48760e7da5.png)

I am not entirely sure if this is intended however I think it's not as it does not display in other mailclients that I'd know of.

Any help required to reproduce this please let me know.

Thanks!

**Comment by TedGoas** [comment] 2020-06-26 21:16
🤔 a few questions:

1. How / where did you add that red color?
2. You only see this in win10 Outlook Mail on desktop?

**Comment by vz01d** [comment] 2020-06-27 07:28
it's on the td wrapping that hero image, I changed the background to red for more visibility:

```html
<!-- Hero Image, Flush : BEGIN -->
<tr>
    <td style="background-color: red;">
        <img src="https://via.placeholder.com/1360x600" width="680" height="" alt="alt_text" border="0" style="width: 100%; max-width: 680px; height: auto; background: #dddddd; font-family: sans-serif; font-size: 15px; line-height: 15px; color: #555555; margin: auto; display: block;" class="g-img">
    </td>
</tr>
<!-- Hero Image, Flush : END -->
```
Yep only on mail, tested with almost all others from thunderbird to gmail to android mail. Some Version Info:

![grafik](https://user-images.githubusercontent.com/52013886/85917151-0e040a00-b858-11ea-8715-d73ff018be86.png)

**Comment by TedGoas** [comment] 2020-06-28 17:36
@vz01d Thanks for the details. I'll dig into this when I can. Presently I don't have access to a Windows machine or a Litmus account, so it may take a while.

**Comment by vz01d** [comment] 2020-06-28 20:35
Alright thank you. I will take a shovel and help digging if I find some free minutes during the week. However I am not that used to mail templates so could take even longer. 🤐🙈

**Comment by TedGoas** [comment] 2020-08-11 20:54
Finally getting to this, but I'm having trouble reproducing this using Email on Acid. I've changed the background color not he wrapping `<td>` to red, but it doesn't show in Outlook 2016 (Win10) or Outlook 1029 (Win10).

![Screen Shot 2020-08-11 at 4 50 47 PM](https://user-images.githubusercontent.com/1172461/89947683-dcba8000-dbf2-11ea-91e9-abbb47da2dc9.png)

I don't suppose you were able to make any progress on your end?

**Comment by TedGoas** [comment] 2020-09-18 00:00
@vz01d Are you still having this issue? If you didn't see my comment above, I'm having trouble reproducing this.

**Comment by TedGoas** [comment] 2020-11-23 01:22
@vz01d Hi, I still cannot reproduce this in any version of Win10 Outlook using Email on Acid:

<img width="704" alt="Screen Shot 2020-11-22 at 8 20 21 PM" src="https://user-images.githubusercontent.com/1172461/99922777-43762c00-2d00-11eb-890f-c6bde4e8745c.png">

I'm gonna close this for now, but feel free to reopen it if you still see the issue and can provide steps to reproduce it. ✌️

**Closed as completed by TedGoas** 2020-11-23 01:22 UTC
