### ISSUE TITLE
1 px horizontal gap in Windows 10 Outlook 2016

### ISSUE THREAD

**Issue by jonaddamstpg** [emailmonday/Cerberus#115] opened 2017-06-05 15:46 UTC
**Issue:** 1 px horizontal gap in Windows 10, Outlook 2016 displays if content has different vertical heights.

**Steps to duplicate:** In the hybrid template, change the two column or three column placeholder text content so that it has different vertical heights. A 1 px horizontal gap will appear that is the same color as the template background. See the screenshot below:
![image](https://cloud.githubusercontent.com/assets/8644458/26790268/1c80f658-49e1-11e7-83fa-a16210925f23.png)

**Affected clients:** Windows 10, Microsoft Outlook 2016

I found a thread discussing the same/similar issue on Litmus: https://litmus.com/community/discussions/4990-outlook-2016-1px-horizontal-lines-showing-up-in-the-body 
I tried suggested solutions from that thread but haven't found any resolutions that work for this template.

**Comment by TedGoas** [comment] 2017-06-05 20:20
@jonaddamstpg I am having trouble reproducing this. ATM I don't have access to an actual copy of Outlook 2016 on Windows 10. **Is that what you're using?**

I _do_ have access to Litmus previews and don't see the bug there:

<img width="982" alt="screen shot 2017-06-05 at 4 17 26 pm" src="https://cloud.githubusercontent.com/assets/1172461/26801395/c3572bea-4a0a-11e7-9b94-97794628c307.png">

**Comment by jonaddamstpg** [comment] 2017-06-05 20:39
I couldn't reproduce in Litmus either. A client pointed this issue out after our regular Litmus tests looked ok. The only difference I could tell from their setup and Litmus was they are on Windows 10 not 7. (I only see the option of Outlook 2016 on Windows 7 in Litmus, and no way to select Windows 10 with Office 2016)
![image](https://cloud.githubusercontent.com/assets/8644458/26802050/07a17790-4a0d-11e7-89d0-3d585e23ec77.png)

I'm on MacOS and don't have a PC or Windows so I downloaded a trial version of Parallels and installed a Windows 10 VM image from Microsoft. Then I installed Outlook 2016 and now I can reproduce. It was a few hours of downloading/installing but this seems like a very common use case so I think it was worth it.

https://developer.microsoft.com/en-us/windows/downloads/virtual-machines
http://www.parallels.com/products/desktop/

**Comment by TedGoas** [comment] 2017-06-07 19:57
@jonaddamstpg I have Parallels and Win10 up, but how can I get a copy of [Outlook 2016](https://www.microsoft.com/en-us/store/d/outlook-2016/cfq7ttc0k5cf?WT.mc_id=pointitsem+Microsoft+Bing+Ads+Outlook+-+EN&cl_vend=bing&cl_ch=sem&cl_camp=240011215&cl_adg=1427357056&cl_crtv=13675309520&cl_kw=outlook%202016&cl_pub=bing.com&cl_dvt=c&cl_mt=e&cl_gtid=kwd-84035995382&cl_dim0=WThaagAAAHHbUz6L:20170607195626:s&s_kwcid=AL!4249!10!13675309520!84035995382&ef_id=WThaagAAAHHbUz6L:20170607195626:s)?

**Comment by jonaddamstpg** [comment] 2017-06-07 20:21
Fully installed Office 2016, 1 month trial:
https://products.office.com/en-us/try

**Comment by TedGoas** [comment] 2017-06-20 16:48
@jonaddamstpg Hmm, I'm probably not going to get to this anytime soon 🙁. Any chance you can help test?

**Comment by jonaddamstpg** [comment] 2017-06-20 17:22
I can test. What do you need?

**Comment by TedGoas** [comment] 2017-06-20 17:43
If you've got Parallels/Win10/Outlook 2016 all set up, see if you can fiddle with the code and find a fix. I'm not sure where to start.

I'm in the process of moving, so I'm not gonna have time to look at this for a few weeks.

**Comment by jonaddamstpg** [comment] 2017-06-20 18:07
I tried to do my due diligence before submitting. I've tried most of the suggestions in this thread but nothing has worked so far:
https://litmus.com/community/discussions/4990-outlook-2016-1px-horizontal-lines-showing-up-in-the-body

This is not an emergency. I've told our clients that this is an Outlook defect and we'll try to find a resolution but no promises. 

Here's the MS Technet thread for reference:
https://social.technet.microsoft.com/Forums/ie/en-US/1f4f1e03-8ad5-4079-bc18-8fcaaa7b785d/outlook-2016-renders-horizontal-lines-seemingly-randomly-in-html-emails?forum=Office2016ITPro

**Comment by istvan-ujjmeszaros** [comment] 2019-02-21 20:39
FYI I think this is a random rendering issue in Windows 10 Mail and Outlook 2016, and the issue is so random that if you open the same email multiple times then sometimes the line will be there and other times it will not be visible (so sometimes everything looks good with the same email in the same client). Probably a hardware acceleration issue which may depend on the VGA hardware too.

I think it happens when there is at least one resized image in the email and the resized height is not a round number. Like when you use a double sized retina image with an odd number height (like 1280x799 resized to 640x399.5). The line may appear in a totally different part when the resized image is that's why it was extremely hard to figure out how it happens.

I wrote a small script that I was running from the console but it requires jquery to be injected with a browser extension or just load jquery temporarily in the email.

`var i=0; $('*').each(function(){var h=$(this).height();if (parseInt(h) !== h) {i++;console.log($(this),$(this).height());$(this).css('background-color','yellow');}}); if (i == 0) {console.log("All heights are integers!")} else {console.log('There are ' + i + ' problematic elements.')}`

**Comment by TedGoas** [comment] 2019-02-22 14:13
@istvan-ujjmeszaros thanks for digging into this. The half-pixel theory makes sense and would explain why this behavior is so inconsistent and hard to reproduce.

@jonaddamstpg realize this bug is super old, but are you still experiencing this issue?

I'm leaning towards closing this as `can't fix`, but am open to discussing it further if we can fix it.

**Comment by jonaddamstpg** [comment] 2019-02-22 14:39
I still see it intermittently. I found a Litmus thread<https://litmus.com/community/discussions/5286-mysterious-white-line-in-outlook> where others were experiencing the same thing and it might be caused/affected by using dir=”rtl”. I have limited my use of rtl and that does help, but I haven’t been able to find a 100% solution.

Jon

**Comment by istvan-ujjmeszaros** [comment] 2019-02-22 22:20
Padding on td's that have `dir="rtl"` can also trigger a similar issue (I am not sure if it is the same). I am just using an additional table inside and adding the padding to that inner table instead.
Someone states in that Litmus thread that "The movement of the dir attribute to start of the <td> tag appeared to fix the issue" but I think it was probably just looked good because the issue is sometimes not visible with the same email (so he may thought that it fixed the issue while it probably didn't).

An other thing I noticed is if the difference between the line-height and font-size is an odd number then that can trigger this line artifact too, but I am really not sure about this, it is just a suspicion.

**Comment by TedGoas** [comment] 2019-02-25 17:30
Hmm, what's strange about the `dir="rtl"` theory is the [part of the template](https://github.com/TedGoas/Cerberus/issues/115#issue-233630579) @jonaddamstpg originally reported as buggy [doesn't use the `dir` attribute](https://github.com/TedGoas/Cerberus/blob/master/cerberus-hybrid.html#L324).

Is the thought that if a `dir="rtl"` appears _anywhere_, it can throw off the template?

---

The "line-height and font-size being an odd number" theory builds a case for a larger "half-pixel theory" case, no?

**Comment by jonaddamstpg** [comment] 2019-02-25 17:36
I’m not sure. I haven’t been able to reproduce the issue consistently. I think what it will take is actually trying some of these theories until its reproducible every time.

Jon

**Comment by istvan-ujjmeszaros** [comment] 2019-02-25 19:39
I am not 100% sure if `line-height` can cause the issue but it was suspicious so I wanted to mention it.

What makes this line artifact issue worse is that I think we can never create a 100% reproducible test case as the same email may sometime show the line artifact and sometime may look good (I have noticed it when I was using the keyboard to go to the next email in my Windows Mail email list and then back to the test email multiple times - the line was not always visible, but most of the time it was (~90% of time it was there, I think that's why everyone may think that the issue is fixed when it is not visible on a test, while it may not be really fixed unfortunately).
High DPI Outlook should be tested too as I think the same email may look good on a normal screen and may look bad on a high dpi screen (for example a 101px tall image is resized to 121.2px on 120DPI).

The `dir="ltr"` issue is a different one, but it also results in line artifacts. It happens when there is a padding on the same `td` where `dir="ltr"` is defined on, and can be avoided by using a nested table and add the padding on that instead (so always use zero padding on the `td` where the dir="ltr" is defined). More info on the `dir="ltr"` issue is in this thread on Litmus: https://litmus.com/community/discussions/5286-mysterious-white-line-in-outlook

I think `dir="ltr"` is always causing the line at the element where it is defined, while the half pixel height can create a line anywhere after the element with the half pixel height (there was a line at the end of an email once when a large logo was resized in the header). @2x sized retina images doesn't seem to trigger this issue, so it is fine to resize something like an 1200x800 image to 600x400.

**Comment by TedGoas** [comment] 2019-02-25 22:10
I'm still confused by the `dir` attribute causing an issue on the two column layout [even though it's not used there](https://github.com/TedGoas/Cerberus/issues/115#issuecomment-467102019).

**The bigger problem is currently I can only test Outlook using Litmus, and this bug doesn't show up there.** I'm not set up to fix this. 😕

This bug seems like an edge case. If we can address this issue by tweaking odd font sizes and line heights, that's an easy fix I can live with. But I'm not super enthusiastic about a fix that requires removing the `dir` attribute (removing functionality) or nesting additional tables (increasing entropy). 

If the `dir` attribute is truly the culprit, documenting this might be the better option. How do y'all feel about this?

**Comment by istvan-ujjmeszaros** [comment] 2019-02-25 23:08
Unfortunately I couldn't reproduce it either (tried in my Windows 10 Mail and in testi@ with no luck).
But FYI the color of the line is the same as the background color of the container element, so if the background would be red, then the line would be red too. I am using a different container in my emails with three columns, and the background color is only been set on these columns. The center column has white background, so the line in Outlook should also be white hence invisible. If I need to use a different background on a section then I define the background color on that column. The drawback of that container is that if the email is larger than 102KB then the whole layout breaks in gmail (the content will not be centered). But I think it can be fixed by adding a center tag around that table (but do not define any background color on the center tag or on the body).

```html
<body>
  <table class="wrapper" style="border-spacing:0;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;font-family:sans-serif;color:#323232;" width="100%">
    <tr>
      <td class="wrapper-left" style="padding:0;background-color:#222222;font-size:0;">&nbsp;</td>
      <td class="content-body-wrapper" style="padding:0;width:680px;background-color:#ffffff;min-width:300px;" width="680">
        <table class="content-body" style="border-spacing:0;table-layout:fixed;min-width:300px;" width="100%">
          <!--- Begin: columns -->
          <!--- End: columns -->
        </table>
      </td>
      <td class="wrapper-right" style="padding:0;background-color:#222222;font-size:0;">&nbsp;</td>
    </tr>
  </table>
</body>
```

**Comment by istvan-ujjmeszaros** [comment] 2019-02-27 21:43
I have just noticed that this issue was opened years ago. I agree that this issue can be closed as it may have been already fixed both in Windows 10 Mail and in Outlook 2016. I wouldn't document it until someone else runs into the same issue.

**Comment by TedGoas** [comment] 2019-02-28 01:32
@istvan-ujjmeszaros Heh, I wouldn't close this based on the issue date alone. Outlook doesn't update itself and there are a lot of folks stuck on old versions. But... I'm leaning towards closing this since the issue is so hard to reproduce and fix. the discussion in this thread *is pretty good documentation* that we can point to if this issue comes up again.

@jonaddamstpg How do you feel about this?

**Comment by istvan-ujjmeszaros** [comment] 2019-02-28 02:40
Actually I could just find an email from 2016 where I was struggling with the lines, and you were right that neither Windows Mail or Outlook 2016 got fixed since then. I have run new tests in testi@ and tested on my Windows Mail, the lines are present in the new tests and on my machine too.

This issue and the attached tests are not related to Cerberus (these are really old emails built with my own email framework), but these tests confirm that the issue in my case was caused by the logo image in the header and by using percentage line heights. It would be great to simplify and anonymize those emails but I don't have time right now to do it, and want to share my finding. I hope it helps.

Here is the original version of the code which looks the worse:
https://testi.at/proj/byQsVnQcP9ESEJgHQQycnLJsL6
https://drive.google.com/open?id=1mxWCR_6gne7UzX-c-sZaKXqPFjRhKpvc

This version looks better (no lines in Windows Mail, but looks bad in Outlook 2016, especially in the 120dpi version), the only difference is that I have used the physical size for the logo image in the header (it was accidentally resized in the first version, but all the images are in their original size in that one):
https://testi.at/proj/gmDCgz3FQX1tOEFAjSLJOhX9
https://drive.google.com/open?id=1L11QXP94jtrYOaAbVWZIyBZdUWMgKyB5

This is the final version with no issues (no lines in any test), I was using exact line-heights in that instead of percentage line heights:
https://testi.at/proj/04jslL6Tj5zSzn8SvAMS4NjClo
https://drive.google.com/open?id=1d328JzCGgEA-nQdc5d4BeB8uDk_s1pw_

**Comment by TedGoas** [comment] 2019-03-01 22:43
At this point, we've diagnosed the 💩 out of this!

@jonaddamstpg @istvan-ujjmeszaros I can't thank you enough for all the legwork you've done in providing screenshots and test cases, and poking at the code. **You've done a great job isolating this bug and provided great documentation and suggestions for anyone who encounters this in the future.**

Since we can't reliably fix this in the Cerberus templates, I'm going to close this as `cant-fix`.

I'll always remember issue #115, should this issue come up again!

Thanks again! ✌️

**Closed as completed by TedGoas** 2019-03-01 22:43 UTC
Labels: cannot-fix

**Comment by RKAN** [comment] 2019-09-26 09:12
Hello,
im have the same issue in **Outlook 2013 (Windows 10)** and **Android 5.1.** (Using latest cerberus-hybrid.html) See here:

![image](https://user-images.githubusercontent.com/164545/65675018-c690e900-e04d-11e9-9e90-f61ff49e3924.png)
![image](https://user-images.githubusercontent.com/164545/65675032-cb559d00-e04d-11e9-8c82-617f488729de.png)

For me this Bugs happens when the attribute "dir" and padding is used in the same element. I solved this issue by changing **padding: 10px** to **border:10px solid #fff;** I dont know if this solutions is the right one but it fixes the Problem, see here:
![image](https://user-images.githubusercontent.com/164545/65675344-4f0f8980-e04e-11e9-82b7-c88097353382.png)
![image](https://user-images.githubusercontent.com/164545/65675368-5d5da580-e04e-11e9-8dd6-cebec0e4f8dc.png)

I want to share it with you all :)

**Comment by istvan-ujjmeszaros** [comment] 2019-09-26 13:14
This is a different issue. You can't use padding on the same element where dir is specified, so the padding must be 0 on that element, and you must put an additional table inside that element and define the padding on that instead.
