### ISSUE TITLE
Media queries ignored in Gmail iOS

### ISSUE THREAD

**Issue by heathflohre** [emailmonday/Cerberus#218] opened 2019-05-07 14:43 UTC
It seems that line 49-51 is causing the media queries to be ignored by Gmail on iOS.

```
/* What it does: Centers email on Android 4.4 */
        div[style*="margin: 16px 0"] {
            margin: 0 !important;
        }
```

**Comment by TedGoas** [comment] 2019-05-07 15:18
@heathflohre I don't understand. Can you explain what you're seeing and in which iOS Gmail product (iMAP, GSuite, etc.).

**Comment by heathflohre** [comment] 2019-05-07 15:36
I was working with the hybrid template and was testing a custom email,
viewing it in Gmail (browser), iOS Mail, and iOS Gmail (with a GSuite
account and regular Google/Gmail account). Gmail (browser) and iOS Mail
displayed as expected, but the media query enhancements weren't displayed.
I went back to the source hybrid template and did the same test and had the
same result. After stepping through the CSS, removing and adding back to
narrow it down, it seems iOS Gmail doesn't like the following styles in
lines 48-51:

/* What it does: Centers email on Android 4.4 */
        div[style*="margin: 16px 0"] {
            margin: 0 !important;
        }

Once removed, the media query enhancements for both my custom email and the
source hybrid template displayed properly.

**Comment by TedGoas** [comment] 2019-05-08 20:39
@heathflohre I'm having trouble reproducing this, can you send me a screenshot of the broken email you're seeing?

---

This is what I see in iOS Gmail with GSuite:
![IMG_F8DB04E38938-1](https://user-images.githubusercontent.com/1172461/57406853-cc298780-71af-11e9-9428-4677b2abae6a.jpeg)

---

And this is what I see in Litmus for iOS Gmail (not sure which product):
![gmailios-vertical-allowed-1366](https://user-images.githubusercontent.com/1172461/57406871-da77a380-71af-11e9-8233-6b67b90d9c1d.png)

**Comment by TedGoas** [comment] 2019-05-17 14:02
@heathflohre Ping! ☝️ did you see my comment from last week?

**Comment by heathflohre** [comment] 2019-05-20 18:27
If I add an additional CSS style, like

```
.email-container p {
  font-size: 17px !important;
  color: red;
 }
```
to the end of the media queries in the progressive enhancement section of the current cerberus-hybrid.html file, I see this in Gmail for iOS.

![IMG_4081](https://user-images.githubusercontent.com/750447/58043348-ebf37080-7b0a-11e9-8e7a-63b44eb8ae2e.PNG)

Keeping the added CSS, if I comment out lines 50-52, I see this in Gmail for iOS.

![IMG_4082](https://user-images.githubusercontent.com/750447/58043450-3379fc80-7b0b-11e9-9664-f3f48b49612f.PNG)

These are screen shots from an iPhone on iOS 12.3. Something about that CSS style blocks the media queries.

**Comment by heathflohre** [comment] 2019-05-20 18:29
The tests were sent through Mailchimp.

**Comment by TedGoas** [comment] 2019-05-20 20:11
@heathflohre Hmm, for the life of me I just cannot reproduce this. I made the body text red using your code above and see the text successfully display in red in both iOS IMAP Gmail as well as in Litmus (screenshots below).

If you don't need lines `49-51` for your project, you can safely remove them if it fixes your issue. I'll dig into if we still _need_ lines `49-51`, but I can't fix this issue since I can't repro it.

---

![IMG_4B5770CA60D5-1](https://user-images.githubusercontent.com/1172461/58048409-b6558400-7b18-11e9-9505-cf6fae20542f.jpeg)

![image](https://user-images.githubusercontent.com/1172461/58048389-a89ffe80-7b18-11e9-84ab-719257a139e5.png)

**Comment by TedGoas** [comment] 2019-05-28 12:47
@heathflohre did you see my comment ☝️ ?

**Comment by TedGoas** [comment] 2019-05-31 12:48
@heathflohre I still can't reproduce the bug you're seeing.

**Comment by heathflohre** [comment] 2019-06-04 18:23
Sorry for the delay. It looks like it’s specific to Mailchimp and how it sends out the emails. It looks fine when testing from other services. 

—Heath Flohre

On May 31, 2019, at 8:49 AM, Ted Goas <notifications@github.com> wrote:

@heathflohre I still can't reproduce the bug you're seeing.

**Comment by TedGoas** [comment] 2019-06-04 19:13
@heathflohre thanks for following up and clarifying. I'll close this as an issue with Mailchimp, but good to know!

**Closed as completed by TedGoas** 2019-06-04 19:13 UTC
