### ISSUE TITLE
(Hybrid) Mobile-View on Gmail (on Android) has margin issues

### ISSUE THREAD

**Issue by miamimabel** [emailmonday/Cerberus#234] opened 2019-12-19 00:32 UTC
Hello -

In the Hybrid template, the text margins do not line up when using the 2-column row above a 1-column row when viewing in the Gmail app on an Android. Attached is a screenshot.

I had previously reported the same issue for the Outlook mobile view, which currently looks good.

Thanks for looking into this!

![hybrid-screenshot](https://user-images.githubusercontent.com/44374217/71134624-f3781680-21cc-11ea-8ad0-0fd187e39e5f.jpg)

**Comment by TedGoas** [comment] 2019-12-22 16:13
@miamimabel Hi, I'm unable to reproduce this exactly example, but I have a theory about what's going on. **In short, when the hybrid template displays in an email client that doesn't support media queries, the layout will always stack but the margins might not line up exactly in some places.**

---

This is what i see when I place a 1 column text after two even columns in a version of Gmail that doesn't support media queries:

![Screen Shot 2019-12-22 at 11 05 04 AM](https://user-images.githubusercontent.com/1172461/71324299-55759c00-24ab-11ea-8714-99526bc0c4fb.png)

I haven't been able to reproduce this yet.

However in order to get stacking columns without media queries, it involves a clever implementation of `padding`, `min-width`, and `max-width`. Sometimes that leaves `30px` of padding on the edges, but sometimes it leaves `20px` depending on the pattern.

If this is an issue, you can try playing with the `align` attribute of the parent row. Eg. If something was originally aligning `center`, try aligning it `left`. You can also update the `padding` of various `<td>`s, though that will likely have an impact on the desktop layout.

---

Please let me know if you have any luck with the issue. I'll leave this open.

**Comment by TedGoas** [comment] 2020-01-08 21:56
@miamimabel Ping! Did you see my note above? up☝️

**Comment by danielbridge** [comment] 2020-01-10 01:48
![Screenshot_20200109-174228](https://user-images.githubusercontent.com/59715874/72119109-21520600-3308-11ea-8dbe-1e945b15f7ac.png)
Having the same issue with justification on many different platforms. Please help as I love this template and how easy it makes everything!

**Comment by danielbridge** [comment] 2020-01-10 01:51
👆the responsive version

**Comment by TedGoas** [comment] 2020-01-10 13:28
@danielbridge Does this happen with the original source code found in this repo? If so, can you post a screenshot?

**Comment by danielbridge** [comment] 2020-01-10 19:26
![Screenshot_20200110-112351](https://user-images.githubusercontent.com/59715874/72180436-092bc680-339c-11ea-9817-48baf4c6e3ee.png)

**Comment by danielbridge** [comment] 2020-01-10 19:26
![Screenshot_20200110-112400](https://user-images.githubusercontent.com/59715874/72180458-15178880-339c-11ea-806f-f0616244f518.png)

**Comment by danielbridge** [comment] 2020-01-10 19:27
![Screenshot_20200110-112413](https://user-images.githubusercontent.com/59715874/72180468-1fd21d80-339c-11ea-83b0-e35f8d3af620.png)

**Comment by danielbridge** [comment] 2020-01-10 19:28
This is all just the original code pasted into a blank page on WordPress and viewed on Moto z3 using chrome.

**Comment by TedGoas** [comment] 2020-01-10 20:42
> pasted into a blank page on WordPress

I'm confused. This bug reported some odd behavior in mobile-view on Android Gmail. How does Wordpress figure in?

**Comment by danielbridge** [comment] 2020-01-10 21:17
Its a link to the "view in as a webpage" sorry may be a separate issue and would require a separate thread. Is this code not supposed to be viewed outside of an email client? I was maybe confused by that wording as I assumed it would be able to be used as a standalone. Basically just put a link to the html doc onto my website via wordpress as a link to the "view as a webpage"  text. Please help I really admire and papreciate your work as it makes complicated things easier for people like me thanks!

**Comment by TedGoas** [comment] 2020-01-10 23:12
Yeah I think that's a separate issue. The code can be viewed outside an email client, though I'm not sure how Wordpress (or whoever) is creating the `view in as a webpage` page.

**Comment by TedGoas** [comment] 2020-11-23 01:14
I'm still unable to reproduce the original bug reported in this issue. Closing this for now, but please reopen if you still see the issue and can provide steps to reproduce. ✌️

**Closed as completed by TedGoas** 2020-11-23 01:14 UTC
