### ISSUE TITLE
IOS 13.5.1 latest version causing alignment issues for email in outlook app

### ISSUE THREAD

**Issue by zubin89** [emailmonday/Cerberus#245] opened 2020-06-18 07:27 UTC
I checked emails in my outlook app in IPhone and all CTA and links which are aligned center got to left.

It is rendering fine in android phones , desktop (gmail or outlook or yahoo or hotmail) or webmails. 

It looks like an outlook app rendering issue in IOS latest version. I updated the IOS to the latest version 13.5.1 recently. 
In previous version it was not the same case

**Comment by TedGoas** [comment] 2020-06-18 23:16
@zubin89 Hi, which template are you using? I'm having trouble reprpducgint this using the `Hybrid` template using Outlook on my iPhone:

![IMG_69E6B579C238-1](https://user-images.githubusercontent.com/1172461/85080842-37f26800-b198-11ea-802d-3879b73311bf.jpeg)

Buttons are still centered.

**Comment by zubin89** [comment] 2020-06-19 02:22
Hey Ted I am also using hybrid template and the rendering is showing correct in gmail but not in outlook. Please see below screenshots

Gmail app in iphone 
![A3CB1218-081E-4AB4-AE56-59A81A93C39B](https://user-images.githubusercontent.com/8589017/85090042-b988db00-b216-11ea-90f9-35fb2eff98a9.png)

Outlook app in Iphone
![612F1486-5902-4EE9-B50E-3A3D2839C73B](https://user-images.githubusercontent.com/8589017/85090071-cc9bab00-b216-11ea-8717-29933fd745ae.png)
![190D4727-9A98-461F-A5BA-496AA9AA63CA](https://user-images.githubusercontent.com/8589017/85090083-d3c2b900-b216-11ea-8ec8-d5eebfb2c710.png)

**Comment by TedGoas** [comment] 2020-06-19 12:01
@zubin89 Can you reproduce this with the latest copy of the Hybrid template from this repo?

**Comment by zubin89** [comment] 2020-06-19 12:16
I cannot find the copy of hybrid template here. Is it possible you can send me template to my email so i can check - zubinpandit@gmail.com

**Comment by TedGoas** [comment] 2020-06-19 16:33
@zubin89 Send yourself a copy of this and lemme know what you see:
https://github.com/TedGoas/Cerberus/blob/main/cerberus-hybrid.html
https://raw.githubusercontent.com/TedGoas/Cerberus/main/cerberus-hybrid.html

**Comment by TedGoas** [comment] 2020-06-29 14:06
@zubin89 Checking in on my previous comment, have you tried sending yourself a test using the code in this repo?

**Comment by TedGoas** [comment] 2020-07-03 03:25
@zubin89 Gonna close this for now since your issue doesn't seem to be from the original code found in this repo. Happy to keep chatting here, though.

**Closed as completed by TedGoas** 2020-07-03 03:25 UTC
