### ISSUE TITLE
Outlook 2016 - fluid template - background missing

### ISSUE THREAD

**Issue by laughingguffly** [emailmonday/Cerberus#84] opened 2016-10-24 10:20 UTC
Firstly, great project!
I've run the source code of fluid template through putsmail and sent to outlook 2016 and the background is missing. There is also a gap at the top of the email.

**Comment by TedGoas** [comment] 2016-10-24 14:07
@laughingguffly can you attach a screenshot of what you see?

**Comment by laughingguffly** [comment] 2016-10-24 14:20
I've changed the images on this one, but the result is the same.

![unnamed](https://cloud.githubusercontent.com/assets/12569981/19649338/6233780e-99fd-11e6-9fd0-fc157b4b45f5.jpg)

**Comment by laughingguffly** [comment] 2016-10-24 14:23
and here is the lower half.

![bottom](https://cloud.githubusercontent.com/assets/12569981/19649454/c374cb4a-99fd-11e6-8365-e1fda42b4c32.jpg)

**Comment by TedGoas** [comment] 2016-10-25 00:19
@laughingguffly Hmm, I don't include background images on the **Fluid** template, but I do on the **Hybrid** one. I ran them both through Litmus and don't see the issues you describe above. If you view the latest, unedited templates in Outlook 2016, do you see something like the images below?

**Fluid**
![ol2016-vertical-allowed-fluid](https://cloud.githubusercontent.com/assets/1172461/19668632/1096af1e-9a27-11e6-8b29-340efe18bf17.png)

**Hybrid**
![ol2016-vertical-allowed-hybrid](https://cloud.githubusercontent.com/assets/1172461/19668636/15d8eb22-9a27-11e6-9fe7-36e47dcc6658.png)

**Comment by laughingguffly** [comment] 2016-10-25 14:57
Sorry to waste your time. Fixed now and looks great in Outlook 2016.
1. Outlook needed updating.
2. I was using CKEditor to do the editing which was stripping the tags out from your template.

**Comment by TedGoas** [comment] 2016-10-25 17:34
@laughingguffly no waste at all. Thanks for doing a bit of digging on this!

**Comment by laughingguffly** [comment] 2016-10-25 18:15
Hi,

No, if I view the unedited templates in outlook 2016 with latest updates
sent through putsmail the back ground doesn't appear and there is a large
gap at the top.

**Comment by TedGoas** [comment] 2016-10-25 19:48
@laughingguffly I can reproduce the lack of background color, but not the margin. Everything looks fine when testing in Litmus or sending from Campaign Monitor, but I see this when sending from PutsMail.

Have you been able to fix this? I'll see if I can diagnose what's going on, though I don't know how much time I want to spend on this since it seems like a problem with PutsMail.

![hybrid-windows10mail-vertical-allowed-1366](https://cloud.githubusercontent.com/assets/1172461/19701662/558b7624-9aca-11e6-9545-9efba1b70bc3.png)

**Comment by laughingguffly** [comment] 2016-10-26 15:40
Putsmail is cleansing one or more of the tags with the background color that applies to outlook 2016 by the looks of it? 

Not ideal but I was able to make CKEditor turn off all stripping with the commands:
config.allowedContent = true; 
            config.extraAllowedContent = '_(_)';

It would be great if I knew which tag to allow.

**Comment by laughingguffly** [comment] 2016-10-26 21:42
strips out bgcolor amongst many others.

```
<body bgcolor="#222222" lang=EN-GB link=blue vlink=purple style='tab-interval:
36.0pt' width="100%">
```

**Comment by TedGoas** [comment] 2016-10-27 00:14
That is odd. Have you tried `style: background:#222222;` or `style: background-color:#222222;`?

**Comment by laughingguffly** [comment] 2016-10-27 07:04
Yup adding that to the body style at line 8 fixes it:

background:#222222 !important;

**Comment by TedGoas** [comment] 2016-10-28 12:32
That is bizarre, thanks for looking into this. I'd like to run some tests to see if this can be fixed without adding a third background color reference.

**Comment by TedGoas** [comment] 2017-02-23 18:15
Note to self: [this is worth looking into](https://litmus.com/community/discussions/6229-windows-10-mail-vml-background-solution).

**Comment by TedGoas** [comment] 2017-04-04 14:18
Issue seems to have resolved itself (presumably on the Putsmail side of things). Current Cerberus code, without adding an extra `background:#222222 !important;` to the `body` in `<style>`, seems to work in Outlook 2016 Windows.

![ol2016-vertical-allowed-1366](https://cloud.githubusercontent.com/assets/1172461/24661254/ebc279d4-191f-11e7-9097-c782012b68da.png)

![ol2016-vertical-allowed-1366-hybrid](https://cloud.githubusercontent.com/assets/1172461/24661258/ef2f85d0-191f-11e7-8bf2-e80ee9446184.png)

**Closed as completed by TedGoas** 2017-04-04 14:18 UTC
Labels: bug, enhancement
