### ISSUE TITLE
Problem with sending to outlook accounts

### ISSUE THREAD

**Issue by amarcorea** [emailmonday/Cerberus#252] opened 2020-10-28 14:11 UTC
Hi, I've started to use this template and I have a issue when I sent mail from automatic Linux mail, in gmail account works well, but outlook account only see the code of template. 
![Screenshot_20201028-080529_Outlook](https://user-images.githubusercontent.com/18236296/97446802-76d9bc80-18f4-11eb-8f1b-25854f6f7b52.jpg)

Furthermore, when I forwarded the email from gmail to outlook account, I can see the template very well, Is there correct form to see the template from outlook without forward?

This is my code
cat responsive-template.html | mail -s "$(echo -e "Test template $(date +%Y-%m-%d" "%H:%M:%S)\nContent-Type: text/html")" myaccount@outlook.com

**Comment by TedGoas** [comment] 2020-10-28 14:27
@amarcorea Unfortunately I don't know anything about automatic Linux mail, but these templates are basic HTML/CSS so I don't think it's a problem with the templates. Have you tried sending other HTML email from automatic Linux mail?

**Comment by jpmeeker** [comment] 2020-10-28 15:11
@amarcorea this is definitely an issue with your script or your box's implementation of mail. I would look at the raw message that's getting sent—my bet is that it's not including the HTML as a mime part but just outputting the HTML as plain text or the mime part is malformed. 

If you're wanting to trigger emails out of your linux box I think you'd be better off using sendmail or installing something than trying to rely on just the mail command. It's been a while since I've relied on same system sending, but if memory serves Mutt does a fairly good job of handling HTML email. You could also use curl and make API calls to something like MailGun (their free tier allows 5k sends per month) and get better deliverability.

**Comment by TedGoas** [comment] 2020-11-23 01:38
@amarcorea Sinc this doesn't seem like an issue with the template markup, I'm gonna close this for now. Feel free to reopen if you still see the error and can provide steps to reproduce. ✌️

thx for adding more color @jpmeeker ❤️

**Closed as completed by TedGoas** 2020-11-23 01:38 UTC
Labels: Not a Bug, question
