### ISSUE TITLE
Clear Spacer

### ISSUE THREAD

**Issue by manavecplan** [emailmonday/Cerberus#155] opened 2018-02-28 16:00 UTC
When I add the code for Clear Spacer after the Email Body, the code works just once i.e. I see appropriate spacing for one spacer. This isn't platform-specific so I'm probably missing something here.

**Comment by TedGoas** [comment] 2018-02-28 17:47
@manavecplan Have you tried something like this?

    
    <tr>
        <td aria-hidden="true" height="1" style="font-size: 0; line-height: 0;" bgcolor="red">
            &nbsp;
        </td>
    </tr>
    

Or this, if you want some padding:

    
    <tr>
        <td style="padding: 20px;">
            <table role="presentation" cellspacing="0" cellpadding="0" border="0" align="center" width="100%">
                <tr>
                    <td aria-hidden="true" height="1" style="font-size: 0; line-height: 0;" bgcolor="red">
                        &nbsp;
                    </td>
                </tr>
            </table>
        </td>
    </tr>

**Comment by TedGoas** [comment] 2018-03-10 20:25
@manavecplan did you have any success with the code above?

**Comment by TedGoas** [comment] 2018-03-21 21:50
@manavecplan Lemme know if you further questions. Gonna close this for now since it's not a bug in the repo's code.

**Closed as completed by TedGoas** 2018-03-21 21:50 UTC
Labels: question
